name: Self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  selftest:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: ./

